package ccssdk

const (
	CCS_ENDPOINTS     = ""
	CCS_MQ_ENDPOINT   = "CCS_MQ_ENDPOINT"
	CCS_MQ_REQ_TOPIC  = "CCS_MQ_REQ_TOPIC"
	CCS_MQ_RESP_TOPIC = "CCS_MQ_RESP_TOPIC"
	CCS_APP_ID        = "CCS_APP_ID"
	CCS_SERVICE_ID    = "CCS_SERVICE_ID"
	CCS_SECRET_KEY    = "CCS_SECRET_KEY"
)
